services:
  - type: web
    name: chat-studio-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
      - key: PORT
        fromService:
          type: web
          name: chat-studio-server
          property: port
    disk:
      name: chat-studio-data
      mountPath: /var/data
      sizeGB: 1